program Util;

uses
  Forms,
  Windows,
  unFuncoes in '..\unFuncoes.pas',
  unPergunta in '..\unPergunta.pas' {FormPergunta},
  unerro in '..\unerro.pas' {frmErro},
  unMensagem in '..\unMensagem.pas' {FormMensagem},
  unDataModule2 in '..\unDataModule2.pas' {dm2: TDataModule},
  unConfiguraGeral in '..\ModCadast\unConfiguraGeral.pas' {frmConfiguracaoGeral},
  unSobre in '..\unSobre.pas' {frmSobre},
  unTeste in '..\unTeste.pas' {FrmTeste},
  unDataModule in '..\unDataModule.pas' {dm: TDataModule},
  unPadrao in '..\unPadrao.pas' {Padrao},
  unAcessos in '..\unAcessos.pas' {FmDireitos},
  unCadastrarSenhas in '..\unCadastrarSenhas.pas' {frmCadastrarSenhas},
  unMudancaSenha in '..\unMudancaSenha.pas' {frmMudancaSenha},
  unMenu in 'unMenu.pas' {Menu},
  unAcesso in '..\unAcesso.pas' {frmAcesso},
  unDataModule3 in '..\unDataModule3.pas' {dm3: TDataModule},
  unFiltroRel in 'unFiltroRel.pas' {frmFiltroRel},
  unpreview in '..\unpreview.pas' {FormPreview},
  unOffice in 'unOffice.pas' {frmOffice},
  unRelOffice in 'unRelOffice.pas' {frmRelOffice},
  unVisualizarRel in '..\unVisualizarRel.pas' {FrmVisualizarRel},
  unSplash in '..\unSplash.pas' {FormSplash},
  unErrosConversaoString in '..\unErrosConversaoString.pas' {frmErrosConversaoString},
  unPergunta3 in '..\unPergunta3.pas' {FrmPergunta3},
  unPergunta2 in '..\ModAdmin\unPergunta2.pas' {FrmPergunta2},
  unFiltroAgenda in '..\ModAdmin\unFiltroAgenda.pas' {frmFiltroAgenda},
  unRelAgenda in '..\ModAdmin\unRelAgenda.pas' {frmRelAgenda: TQuickRep},
  unConsultaTabela in '..\unConsultaTabela.pas' {EditArquivo},
  unSqlExplorer in 'unSqlExplorer.pas' {frmSqlExplorer},
  unIntegridades in '..\ModAdmin\unIntegridades.pas' {frmIntegridades},
  unUsuariosLogados in '..\unUsuariosLogados.pas' {frmUsuariosLogados},
  unVerificaIntegridade in '..\ModFinan\unVerificaIntegridade.pas' {frmVerificaIntegridade},
  unEmail in '..\unEmail.pas' {fmEmail},
  unConfigBackup in '..\unConfigBackup.pas' {frmConfigBackup},
  unAguardaBackup in '..\unAguardaBackup.pas' {frmAguardaBackup},
  unRelAcessos in '..\unRelAcessos.pas' {frmRelAcessos},
  unImportaLogTexto in '..\ModComer\unImportaLogTexto.pas' {frmImportaLogTexto},
  unRelImporta_Log2 in '..\ModComer\unRelImporta_Log2.pas' {frmRelImporta_Log2},
  unRelImporta_Log in '..\ModComer\unRelImporta_Log.pas' {frmRelImporta_Log},
  unMigrarDads in 'unMigrarDads.pas' {frmMigrarDads},
  unContatosAgenda in '..\ModCadast\unContatosAgenda.pas' {frmContatosAgenda},
  unTipoContato in '..\ModCadast\unTipoContato.pas' {frmTipoContato},
  unAgenda in '..\ModAdmin\unAgenda.pas' {frmAgenda},
  unRelAgendaSint in '..\ModAdmin\unRelAgendaSint.pas' {frmRelAgendaSint: TQuickRep},
  unRotinas in 'unRotinas.pas' {frmRotinas},
  unRotinasUsuarios in 'unRotinasUsuarios.pas' {frmRotinasUsuarios},
  unFaixaSequencia in 'unFaixaSequencia.pas' {frmFaixaSequencia},
  unBackupNovo in 'unBackupNovo.pas' {frmBackupNovo},
  unSequenciaUnica in 'unSequenciaUnica.pas' {frmSequenciaUnica},
  unAtoCofis15 in 'unAtoCofis15.pas' {frmAtoCofis15},
  unFuncoesFiscais in '..\ModAdmin\unFuncoesFiscais.pas',
  unExportaFiscal in 'unExportaFiscal.pas' {frmExportaFiscal},
  unSubstituirVendedor in '..\ModCadast\unSubstituirVendedor.pas' {frmSubstituirVendedor},
  QRPrev in '..\qrprev.pas' {QRStandardPreview},
  unManegerNFeiGer in '..\unmanegernfeiGer.pas' {frmManegerNFeiGer},
  unCopiaNFe in 'unCopiaNFe.pas' {frmCopiaNFe},
  unArqCaixaUsoEmpresa in '..\ModFinan\unArqCaixaUsoEmpresa.pas' {frmArqCaixaUsoEmpresa},
  unEstadoTO in '..\ModCadast\unEstadoTO.pas',
  unAlerta in '..\ModAdmin\unAlerta.pas' {frmAlerta},
  unFortesCFC in '..\ModAdmin\unFortesCFC.pas',
  unFiltroInventario in '..\ModAdmin\unFiltroInventario.pas' {frmFiltroInventario},
  unRelListagemMateriaisEstoque in '..\ModAdmin\unRelListagemMateriaisEstoque.pas' {frmRelListagemMateriaisEstoque},
  unListagemMateriais in '..\ModAdmin\unListagemMateriais.pas' {frmListagemMateriais},
  unRelListagemMateriais in '..\ModAdmin\unRelListagemMateriais.pas' {frmRelListagemMateriais},
  unRelListagemMateriaisQuant in '..\ModAdmin\unRelListagemMateriaisQuant.pas' {frmRelListagemMateriaisQuant},
  unRelListagemBobinas in '..\ModAdmin\unRelListagemBobinas.pas' {frmRelListagemBobinas},
  unRelBobinaGramatura in '..\ModAdmin\unRelBobinaGramatura.pas' {frmRelBobinaGramatura},
  unRelEstoqueAtual in '..\ModAdmin\unRelEstoqueAtual.pas' {frmRelEstoqueAtual},
  unConfigFiltro in '..\unConfigFiltro.pas' {frmConfigFiltro},
  unListagemMateriaisEstoque in '..\ModAdmin\unListagemMateriaisEstoque.pas' {frmListagemMateriaisEstoque},
  unRelInventario in '..\ModAdmin\unRelInventario.pas' {frmRelInventario},
  unEmpresa in '..\ModAdmin\unempresa.pas' {frmEmpresa},
  unAcessoInterno in '..\unAcessoInterno.pas' {frmAcessoInterno},
  unPesquisa in '..\unPesquisa.pas' {Pesquisa},
  unPafImport in '..\ModPAF\unPafImport.pas' {frmPafImport},
  md5 in '..\ModPAF\md5.pas',
  unUserKey in 'unUserKey.pas' {frmUserKey},
  unManifestacao in '..\ModAdmin\unManifestacao.pas' {frmManifestacao},
  unServerMail in '..\unServerMail.pas',
  unManifestacaoSuporte in '..\ModAdmin\unManifestacaoSuporte.pas',
  unFornecedores in '..\ModCadast\unFornecedores.pas',
  unBancoFornecedor in '..\ModCadast\unBancoFornecedor.pas' {frmBancoFornecedor},
  unClientes in '..\ModCadast\unClientes.pas',
  unClienteSuporte in '..\ModCadast\unClienteSuporte.pas',
  unBancoCliente in '..\ModCadast\unBancoCliente.pas' {frmBancoCliente},
  UnInformacaoComercial in '..\ModCadast\UnInformacaoComercial.pas' {frmInformacaoComercial},
  unAutorizados in '..\ModCadast\unAutorizados.pas' {frmAutorizados},
  unCliFaturamento in '..\ModCadast\unCliFaturamento.pas' {frmCliFaturamento},
  unInformacaoSerasa in '..\ModCadast\unInformacaoSerasa.pas' {frmInformacaoSerasa},
  unHistoricoCliente in '..\ModCadast\unHistoricoCliente.pas' {frmHistoricoCliente},
  unSocios in '..\ModCadast\unSocios.pas' {frmSocios},
  unTrocaMovimentacao in '..\ModCadast\unTrocaMovimentacao.pas' {frmTrocaMovimentacao},
  unListagemHistCliente in '..\ModCadast\unListagemHistCliente.pas' {frmListagemHistCliente},
  unRelHistCliente in '..\ModCadast\unRelHistCliente.pas' {frmRelHistCliente},
  unSedes in '..\ModCadast\unSedes.pas' {frmSedes},
  unSeries in '..\ModCadast\unSeries.pas' {frmSeries},
  unImportarClientes in '..\ModCadast\unImportarClientes.pas' {frmImportarClientes},
  unPedCredito in '..\ModContrato\unpedcredito.pas' {frmPedCredito},
  unEventosClientes in '..\ModCadast\unEventosClientes.pas' {frmEventosClientes},
  unvendedores in '..\ModCadast\unvendedores.pas',
  unCotaVendedor in '..\ModCadast\unCotaVendedor.pas' {frmCotaVendedor},
  unAuditoriaDados in '..\unAuditoriaDados.pas',
  unTransportadoras in '..\ModCadast\unTransportadoras.pas' {frmTransportadoras},
  unCarros in '..\ModCadast\uncarros.pas' {frmCarros},
  unProdutoSuporte in '..\ModCadast\unProdutoSuporte.pas',
  unListagemMovimProdutos in '..\ModAdmin\unListagemMovimProdutos.pas' {frmListagemMovimProdutos},
  unRelListagemMovimProdutos in '..\ModAdmin\unRelListagemMovimProdutos.pas' {frmRelListagemMovimProdutos},
  unRelMovimentacaoSint in '..\ModAdmin\unRelMovimentacaoSint.pas' {frmRelMovimentacaoSint},
  unMovimentoEstoquePAF in '..\ModAdmin\unMovimentoEstoquePAF.pas' {frmMovimentoEstoquePAF},
  unListagemPAF_ESTOQUE in '..\ModAdmin\unListagemPAF_ESTOQUE.pas' {frmListagemPafEstoque},
  unGerarCFe in '..\ModAdmin\unGerarCFe.pas' {frmGerarCFe},
  unSuporteNFSe in '..\ModAdmin\unSuporteNFSe.pas',
  unVendedorSuporte in '..\ModCadast\unVendedorSuporte.pas',
  unSuporteCFe in '..\ModAdmin\unSuporteCFe.pas',
  unPagamento in '..\ModAdmin\unPagamento.pas' {frmPagamento},
  unStatusPagamento in '..\ModAdmin\unStatusPagamento.pas' {frmStatusPagamento},
  unCEP in '..\ModCadast\unCEP.pas' {frmCEP},
  unSuporteFaturamento in '..\ModAdmin\unSuporteFaturamento.pas',
  MSXML2_TLB in '..\MSXML2_TLB.pas',
  uS3Storage in '..\uS3Storage.pas',
  us3thread in '..\us3thread.pas',
  unMensageiro in '..\unMensageiro.pas' {frmMensageiro},
  unEasyPag in '..\..\PVida\unEasyPag.pas' {frmEasyPag},
  Compliance in '..\Compliance.pas',
  PvidaTipos in '..\..\PVida\PvidaTipos.pas',
  unSuporteFinanceiro in '..\ModFinan\unSuporteFinanceiro.pas',
  unGestorDeCliente in '..\ModAdmin\unGestorDeCliente.pas' {frmGestorDeCliente},
  unServerMailLista in '..\unServerMailLista.pas' {frmServerMailLista},
  unClienteCompliance in '..\ModCadast\unClienteCompliance.pas' {frmClienteCompliance};

{$R *.RES}

begin
  Application.Initialize;
  FormSplash := TFormSplash.Create( Application );
  FormSplash.Show;
  FormSplash.Update;
  Application.Title := 'Utilitários';
  Application.CreateForm(Tdm3, dm3);
  Application.CreateForm(Tdm2, dm2);
  Application.CreateForm(Tdm, dm);
  Application.CreateForm(TfrmMenu, frmMenu);
  Application.CreateForm(TFmDireitos, FmDireitos);
  Application.CreateForm(TfrmAcesso, frmAcesso);
  Application.CreateForm(TEditArquivo, EditArquivo);
  Application.CreateForm(TfrmEasyPag, frmEasyPag);
  Application.CreateForm(TfrmServerMailLista, frmServerMailLista);
  FormSplash.Hide;
  FormSplash.Free;
  Application.Run;
  exitprocess(0);
end.
